### ISSUE TITLE
build script "stacksize" option does not work with "test" task 

### ISSUE THREAD

**Issue by core36** [validator/validator.github.io#14]
Hello - newfag here, trying to build on raspberry pi 2:
"python ./build/build.py --stacksize=16384 build" does work.
"python ./build/build.py --stacksize=16384 run" does work
"python ./build/build.py --stacksize=16384 test" crashes with stackoverflow error
so i can't build it with the "all" option.

what can i do to resolve this error?
thanks

**Comment by sideshowbarker** [comment]
I doubt a stack size of 16k is anywhere close to being enough.

**Comment by core36** [comment]
called "python ./build/build.py --help" and got:
"--stacksize=NN sets the Java thread stack size in KB"
so "--stacksize=16384" should be 16MB?
tried "python ./build/build.py --stacksize=16000000 test" but still stack oveflow error and no memory error

calling "run" with a stacksize of 16000000 there is an error stating "Invalid thread stack size -Xss16000000k"

Terminal output ("python ./build/build.py --stacksize=16000000 test"):
"java" -classpath ./dependencies/commons-codec-1.10.jar:./dependencies/commons-fileupload-1.3.1.jar:./dependencies/commons-io-2.4.jar:./dependencies/commons-logging-1.2.jar:./dependencies/commons-logging-1.2-adapters.jar:./dependencies/commons-logging-1.2-api.jar:./dependencies/galimatias-0.1.0.jar:./dependencies/httpcore-4.4.jar:./dependencies/httpclient-4.4.jar:./dependencies/icu4j-54.1.1.jar:./dependencies/javax.servlet-api-3.1.0.jar:./dependencies/jchardet-1.0.jar:./dependencies/jetty-http-9.2.9.v20150224.jar:./dependencies/jetty-io-9.2.9.v20150224.jar:./dependencies/jetty-security-9.2.9.v20150224.jar:./dependencies/jetty-server-9.2.9.v20150224.jar:./dependencies/jetty-servlet-9.2.9.v20150224.jar:./dependencies/jetty-servlets-9.2.9.v20150224.jar:./dependencies/jetty-util-9.2.9.v20150224.jar:./dependencies/jetty-util-ajax-9.2.9.v20150224.jar:./dependencies/log4j-1.2.17.jar:./dependencies/rhino-1.7R5.jar:./dependencies/xom-1.2.5.jar:./jing-trang/lib/saxon9.jar:./jing-trang/lib/xercesImpl.jar:./jing-trang/lib/xml-apis.jar:./jing-trang/lib/isorelax.jar:./jars/htmlparser.jar:./jars/validator.jar:jing-trang/build/jing.jar nu.validator.client.TestRunner --ignore=html-its tests/messages.json
2015-08-03 12:38:32.489:INFO::main: Logging initialized @1299ms
Exception in thread "main" java.lang.StackOverflowError
at com.thaiopensource.relaxng.impl.DuplicateAttributeDetector.startChoice(Unknown Source)
at com.thaiopensource.relaxng.impl.ChoicePattern.checkRestrictions(Unknown Source)
etc... (~300x the last line)

**Comment by sideshowbarker** [comment]
Yeah, I see now from looking at the source that we already have it appending `k` to what you specify.

So, please try `--stacksize=512` or `--stacksize=1024`.

**Comment by core36** [comment]
sorry, no luck with both options.
"build" works without it
"run" needs atleas 4096k or it gives OutOfMemory error
"test" just does not work.
i think it's strange the problem is only with the "test" task. maybe the script does not append the "-XX:ThreadStackSize" and "-Xss" options in the "test" task?
do i need the "test" task or can i skip it somehow?

**Comment by sideshowbarker** [comment]
> i think it's strange the problem is only with the "test" task. maybe the script does not append the "-XX:ThreadStackSize" and "-Xss" options in the "test" task?

ah yeah sorry I think that’s the case actually yeah. I'll try to add support for those options to the `test* task soon.

> do i need the "test" task or can i skip it somehow?

You do not need that `test` task. You can can skip it. It’s mainly there for me to use myself for regression testing.

**Comment by core36** [comment]
thank you for the quick help. you helped me alot. everything runs smooth now.
